### ISSUE TITLE
Method names should match the documented names

### ISSUE THREAD

**Issue by elluminatte** [Imagick/imagick#211]
Hello.

The method names <a href="http://php.net/manual/ru/book.imagick.php">here</a> doesnt match method names, returning by reflection.
For example: 
* Imagick::getimageorientation (by reflection) and Imagick::getImageOrientation (in docs).

Seems that this is because ignoring case in imagick.c.

To my mind methods should follow documented spelling. The reason is static analysis - i use PHPStan and get errors on calling Imagick methods in documented way, that force me to use calls like this - "getimageorientation()".
I undestrand that methods are case-insensitive, but i think that a lot of teams would like to have consistency of calls and this check enforces it.

Hope you would like to fix this.

Regards, Nikolay

**Comment by Danack** [comment]
This is something that could be done for version 4. Other people have commented on it also.

> The reason is static analysis - i use PHPStan and get errors on calling Imagick methods in documented

That is a bug in PHPStan. PHP explicitly does not use case when calling methods.

**Comment by VasekPurchart** [comment]
> That is a bug in PHPStan. PHP explicitly does not use case when calling methods.

It is not actually a bug - this is only part of the [strict rules](https://github.com/phpstan/phpstan-strict-rules), which you can opt in to.

So for now PHPstan is probably correct about this, but it got more complicated because now PHPStan is using (when the extension is not loaded) information from PHPStorm stubs, which uses the camelCase notation - https://github.com/JetBrains/phpstorm-stubs/pull/730

**Comment by Danack** [comment]
Fyi this was fixed in Imagick version 3.5.0.
