### ISSUE TITLE
Help wanted: what versions of ImageMagick have MagickSetImageInterpolateMethod 

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#397]
This [CI run failed due to](https://github.com/Imagick/imagick/runs/2546442829?check_suite_focus=true#step:6:164) MagickSetImageInterpolateMethod not being present in the ImageMagick code.

Can someone look through the sources for ImageMagick 7 branch, and find what is version range where the function MagickSetImageInterpolateMethod is available.

i.e. where is it first reliably usable from?

**Comment by Danack** [comment]
Hi @Munix9

Thanks for taking a look. The place to look though is through the releases of ImageMagick 7 and see in which version that function is present: https://github.com/ImageMagick/ImageMagick/releases

Or it might be possible to find the same info in: https://abi-laboratory.pro/?view=timeline&l=imagemagick

> besides the fact that PHP5 is EOL

long story, short version; I'm maintaining support for 5.x and ImageMagick 6 for the time being as downstream distributions still support them, as there's reasonable chances for security problems that need fixing.

The general plan is to drop support for ImageMagick 6 and php < 7 at the same time. That will depend on Debian and Ubuntu moving to ImageMagick 7, and my understanding is that the hold up for that is that the differences between 6 and 7 are nasty to do smoothly for end-users. But that's the Debian and Ubuntu maintainers problem to deal with.

**Comment by munix9** [comment]
Ok, here's my guess:
[Full PHP 5.6 - I 7.0.1-0](https://github.com/Imagick/imagick/runs/2574669330?check_suite_focus=true) fails because `MagickSetImageInterpolateMethod` is only available from ImageMagick version 7.0.1-1 (see below).
[Full PHP 5.5 - I 7.0.1-0](https://github.com/Imagick/imagick/runs/2574669870?check_suite_focus=true#step:6:163) does not fail because the compiled version is not used for the tests, but the one provided (and installed) by Ubuntu (this seems to be the case for [Full PHP 5.4 - I 7.0.1-0 ](https://github.com/Imagick/imagick/runs/2574667227?check_suite_focus=true#step:6:181) as well).
I assume this because line 163 (181) says `PHP Warning: Module 'imagick' already loaded in Unknown on line 0` and that actually indicates that the module was either compiled into PHP or already loaded.

I didn't find MagickSetImageInterpolateMethod in version [7.0.1-0](https://github.com/ImageMagick/ImageMagick/blob/7.0.1-0/MagickWand/magick-image.h), but it seems to be available from version [7.0.1-1](https://github.com/ImageMagick/ImageMagick/blob/7.0.1-1/MagickWand/magick-image.h#L273).

Does this help you in any way?

**Comment by Danack** [comment]
> Does this help you in any way?

It brings back memories of stuff that I had successfully suppressed... details [now in a comment.](https://github.com/Imagick/imagick/blob/d9e515cea377db9722c7b2d049463055cfaea516/php_imagemagick_version_defs.h#L5)
