### ISSUE TITLE
setImageInterlaceScheme() does not work

### ISSUE THREAD

**Issue by banakito** [Imagick/imagick#627]
Hi,

When I try to set the Interlace Scheme while optimizing an image, I'm getting a wrong result.
Let me explain:

```
$DesiredInterlace = imagick::INTERLACE_PLANE; // 3

// Process Source Image
$im = new Imagick();
$im->readImageBlob($ImageBlob);
$im->setImageInterlaceScheme($DesiredInterlace); // 3 - INTERLACE_PLANE
$OriginInterlace = $im->getImageInterlaceScheme(); // OK. Returns: 3 - INTERLACE_PLANE
$NewBlob = $im->getImageBlob();
...

// Check Target Image
$im2 = new Imagick();
$im2->readImageBlob($NewBlob);
$NewInterlace = $im2->getImageInterlaceScheme() // WRONG. Returns: 1 - INTERLACE_NO
```

I'm running PHP 8.2.9, ImageMagick 7.1.1-15 Q16-HDRI x86_64 and Imagick 3.7.0 on Centos 7.

Best Regards,

**Comment by Danack** [comment]
To set your expectations, that looks like a bug in ImageMagick (the underlying library that does the actual work), rather than in Imagick. Or it could just be the intended behaviour? Dunno.

As a work around, you could try cloning the image  e.g. `$im2 = clone $im;` to see if that preserves the property.

**Comment by banakito** [comment]
Indeed clone works but I need the property preserved in the Blob string.
Maybe the expected behaviour, i'll keep trying.

Thank you very much.
